services:
  redpanda:
    image: redpandadata/redpanda:v23.3.10   # â† new org + tag
    command: >
      redpanda start --overprovisioned --smp 1 --memory 512M
      --advertise-kafka-addr redpanda:9092
      --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"   # Kafka API
      - "9644:9644"   # Admin UI